import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { ExportControls } from '../components/results/ExportControls'
import * as exportsApi from '../api/exports'
import { ApiError } from '../api/client'

describe('ExportControls Component (Phase P24)', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('1. renders export controls, buttons, and neutral descriptive text', () => {
    render(<ExportControls runId="test-run-001" />)

    expect(screen.getByText('Export Results')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Download CSV Package/i })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Download PDF Report/i })).toBeInTheDocument()

    expect(
      screen.getByText(/Machine-readable ZIP containing plan, candidates, conjunction events/i)
    ).toBeInTheDocument()
    expect(
      screen.getByText(/Printable screening summary generated by the D-DATO backend/i)
    ).toBeInTheDocument()

    // Ensure non-operational positioning: no certified safety claims
    expect(screen.queryByText(/certified safety report/i)).not.toBeInTheDocument()
    expect(screen.queryByText(/official report/i)).not.toBeInTheDocument()
    expect(screen.queryByText(/collision assessment/i)).not.toBeInTheDocument()
  })

  it('2. triggers CSV download, shows loading state, and displays success badge', async () => {
    let resolveDownload: (val: string) => void = () => {}
    const downloadPromise = new Promise<string>((resolve) => {
      resolveDownload = resolve
    })
    vi.spyOn(exportsApi, 'downloadRunCsv').mockReturnValue(downloadPromise)

    render(<ExportControls runId="test-run-001" />)

    const csvButton = screen.getByRole('button', { name: /Download CSV Package/i })
    fireEvent.click(csvButton)

    // Loading state
    expect(screen.getByText(/Preparing CSV…/i)).toBeInTheDocument()
    expect(csvButton).toBeDisabled()

    // Complete download
    resolveDownload('d-dato-test-run-001-export.zip')

    await waitFor(() => {
      expect(screen.getByText(/Downloaded d-dato-test-run-001-export.zip/i)).toBeInTheDocument()
      expect(screen.getByRole('button', { name: /Download CSV Package/i })).toBeEnabled()
    })
  })

  it('3. triggers PDF download, shows loading state, and displays success badge', async () => {
    let resolveDownload: (val: string) => void = () => {}
    const downloadPromise = new Promise<string>((resolve) => {
      resolveDownload = resolve
    })
    vi.spyOn(exportsApi, 'downloadRunPdf').mockReturnValue(downloadPromise)

    render(<ExportControls runId="test-run-001" />)

    const pdfButton = screen.getByRole('button', { name: /Download PDF Report/i })
    fireEvent.click(pdfButton)

    // Loading state
    expect(screen.getByText(/Preparing PDF…/i)).toBeInTheDocument()
    expect(pdfButton).toBeDisabled()

    // Complete download
    resolveDownload('d-dato-test-run-001-report.pdf')

    await waitFor(() => {
      expect(screen.getByText(/Downloaded d-dato-test-run-001-report.pdf/i)).toBeInTheDocument()
      expect(screen.getByRole('button', { name: /Download PDF Report/i })).toBeEnabled()
    })
  })

  it('4. displays error message and allows retry when CSV export fails', async () => {
    vi.spyOn(exportsApi, 'downloadRunCsv').mockRejectedValueOnce(
      new ApiError('CSV export is temporarily unavailable.', 500)
    )

    render(<ExportControls runId="test-run-001" />)

    const csvButton = screen.getByRole('button', { name: /Download CSV Package/i })
    fireEvent.click(csvButton)

    await waitFor(() => {
      expect(screen.getByText('CSV export is temporarily unavailable.')).toBeInTheDocument()
    })

    // Retry should be available
    const retryBtn = screen.getByRole('button', { name: /Retry/i })
    expect(retryBtn).toBeInTheDocument()

    // Successful retry
    vi.spyOn(exportsApi, 'downloadRunCsv').mockResolvedValueOnce('retry-success.zip')
    fireEvent.click(retryBtn)

    await waitFor(() => {
      expect(screen.getByText(/Downloaded retry-success.zip/i)).toBeInTheDocument()
    })
  })

  it('5. prevents duplicate simultaneous download triggers', async () => {
    const mockDownload = vi.spyOn(exportsApi, 'downloadRunCsv').mockReturnValue(
      new Promise(() => {}) // never resolves
    )

    render(<ExportControls runId="test-run-001" />)

    const csvButton = screen.getByRole('button', { name: /Download CSV Package/i })
    fireEvent.click(csvButton)
    fireEvent.click(csvButton)
    fireEvent.click(csvButton)

    expect(mockDownload).toHaveBeenCalledTimes(1)
  })
})
